
# golangci-lint run (v1.49.0)

linters-settings:
  govet:
    check-shadowing: true
  gci:
    # Default: ["standard", "default"]
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/xiegeo/seed) # Custom section: groups all imports with the specified Prefix.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
    # Enable custom order of sections.
    # If `true`, make the section order the same as the order of `sections`.
    # Default: false
    custom-order: true

linters:
  enable-all: true # use new linters by default when golangci-lint upgrades, lets not miss any good ideas
  disable:
    # disabled because of generics (last checked: 2022-10-29 https://github.com/golangci/golangci-lint/issues/2649)
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

    # noisy linters
    - exhaustruct # intentionally use zero value 
    - ireturn # seed has lots of dynamics code
    - nlreturn # new line before return
    - wsl # enforce blank line rules
    - lll # long lines
    - godot

    # officially deprecated
    - nosnakecase
    - maligned
    - exhaustivestruct
    - deadcode
    - ifshort
    - varcheck
    - interfacer
    - structcheck
    - golint
    - scopelint

issues:
  exclude-rules:
    - path: "(.+)_test.go"
      linters:
        - maintidx
        - unused
        
    - path: "(.+)_test.go"
      linters:
        - govet
      text: "declaration of \"t\" shadows declaration"

    - path: "demo"
      linters:
        - gomnd # magic numbers allowed in demo
        - varnamelen

output:
  format: line-number